language: node_js

services:
  - mysql

cache:
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email: false

node_js:
  - '8'

before_install:
  - npm i -g npm@^5.5.1
  - mysql -e 'CREATE DATABASE IF NOT EXISTS RAP2_DELOS_APP DEFAULT CHARSET utf8 COLLATE utf8_general_ci'

script:
  - npm install
  - npm run create-db
  - npm run test
  - npm run linter

after_success:
